dist: xenial

language: go

go: 
  - 1.12.x

env: 
  - GO111MODULE=on  

notifications:
  email: false

before_script:
  - go get github.com/mattn/goveralls
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race ./...  # Run all the tests with the race detector enabled
  - $GOPATH/bin/goveralls -service=travis-ci